// This file was generated by gir (fdeaa47) from gir-files (2e2a9ca)
// DO NOT EDIT

use StyleSchemeChooser;
use ffi;
use glib::translate::*;

glib_wrapper! {
    pub struct StyleSchemeChooserWidget(Object<ffi::GtkSourceStyleSchemeChooserWidget>): StyleSchemeChooser;

    match fn {
        get_type => || ffi::gtk_source_style_scheme_chooser_widget_get_type(),
    }
}

impl StyleSchemeChooserWidget {
    //#[cfg(feature = "v3_16")]
    //pub fn new() -> StyleSchemeChooserWidget {
    //    unsafe { TODO: call ffi::gtk_source_style_scheme_chooser_widget_new() }
    //}
}
